export const COMMANDS = {
  PLACE_ROBOT: 'PLACE_ROBOT',
  PLACE_WALL: 'PLACE_WALL',
  REPORT: 'REPORT',
  MOVE: 'MOVE',
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
}

export const DIRECTIONS = {
  NORTH: 'NORTH',
  EAST: 'EAST',
  SOUTH: 'SOUTH',
  WEST: 'WEST',
}
